name: Android OCR tasker plugin CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 'refs/tags/*'  # Trigger on tag push
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: ./gradlew assembleDebug
      - name: Set up Git tag
        id: tag
        run: echo "TAG_NAME=$(git describe --tags)" >> $GITHUB_ENV
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: OCR-arm64-v8a-debug-${{ env.TAG_NAME }}.apk
          path: app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
