name: Android OCR tasker plugin CI

on:
  push:
    branches:
      - master
      - 'refs/tags/*'  # Trigger on tag push
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: gradle
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: ./gradlew assembleDebug
      - name: Set up Git tag
        id: tag
        run: echo "TAG_NAME=$(git describe --tags)" >> $GITHUB_ENV
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: OCR-debug-${{ env.TAG_NAME }}.apk  # Include tag in the APK file name
          path: app/build/outputs/apk/debug/*.apk

  create_release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

  upload_release_asset:
    runs-on: ubuntu-latest
    needs: [build, create_release]
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v2
        with:
          name: OCR-debug-${{ env.TAG_NAME }}.apk
      - name: Upload APK as release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./OCR-debug-${{ env.TAG_NAME }}.apk
          asset_name: OCR-debug-${{ env.TAG_NAME }}.apk
          asset_content_type: application/vnd..package-archive
